### ISSUE TITLE
Entertainment form for SWC spring

### ISSUE THREAD

**Issue by jt14den** [ucsdlib/workshops#11]
Need to get it started.

**Comment by jt14den** [comment]
yo, are you on waffle yet?

**Comment by U2NG** [comment]
had it before, but wasn't getting updates. just authorized to GH

**Comment by U2NG** [comment]
Susan was notified for planning.  Ent form started , waiting to add dates for workshop.

**Comment by U2NG** [comment]
requesting help to submit to RRAS AA. (i think that's what we talked about doing, instead of Susan this time?) Susan mentioned we have some $ left over from the last one, need to see how we can use the funds

**Comment by U2NG** [comment]
Notified Susan about event.  Will get David to sign form.
